"""
Django settings for eCube_UI_2 project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p18d)ho(vxpl*7xa$gw_s57g35&wvvi02mcu3p=!b_g31lu38u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Package Apps
    'django_extensions',

    # Project Apps
    'hotel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'eCube_UI_2.core.LogIn.middleware.LoginRequiredMiddleware',
]

X_FRAME_OPTIONS = 'DENY'

# LOGIN SETTINGS
LOGIN_URL = '/login/'
POST_LOGIN_URL = '/DashBoard/Index'
FORGOT_PASSWORD_URL = '/login/forgot-password/'
LOGIN_CHECK_URL = '/login/check-bli/'
PUSH_DB_NAME = 'HotelMonitor_HB_QA'
HOTEL_BEDS_RPT_TYPE ='HB'
HOTEL_BEDS_AVL_RPT_TYPE ='HBA'
AUTH_USER_MODEL = 'hotel.UserMaster'

AUTHENTICATION_BACKENDS = (
    'eCube_UI_2.core.LogIn.backends.UserAuthenticationBackend',
)

ROOT_URLCONF = 'eCube_UI_2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'eCube_UI_2.cust_context.get_menu_items',
                'eCube_UI_2.cust_context.get_role_master',
            ],
        },
    },
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'eCube_Centralized_DB',
        'USER': 'root',
        'PASSWORD': 'Eclerx#123',
        'HOST': '192.168.131.23',
        'PORT': '3306',
        'OPTIONS': {
            "init_command": "SET foreign_key_checks = 0;",
        },
    }
}


EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp1.eclerx.com'
EMAIL_HOST_USERNAME = 'indiaeclerx\Anand.Sadasivan'                # indiaeclerx\user_id
EMAIL_HOST_PASSWORD = 'xxxxxxxxxxxxx'
EMAIL_HOST_ID = 'Anand.Sadasivan@eclerx.com'                  # email-id i.e. userid@eclerx.com
EMAIL_PORT = 25
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


WSGI_APPLICATION = 'eCube_UI_2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'

HOTEL_MEDIA_ROOT = os.path.join(MEDIA_ROOT, 'hotel/')
HOTEL_UPLOAD_ROOT = os.path.join(HOTEL_MEDIA_ROOT, 'uploads/')

HOTEL_MEDIA_URL = MEDIA_URL + 'hotel/'
HOTEL_UPLOAD_URL = HOTEL_MEDIA_URL + 'uploads/'
 
HOTEL_MEDIA_DOWNLOAD = HOTEL_MEDIA_ROOT + 'downloads/'
HOTEL_MEDIA_UPLOAD = HOTEL_MEDIA_ROOT + 'uploads/'

SERVICES_IP = 'localhost:5000'
DJANGO_BASEURL = 'localhost:8000'

try:
    from eCube_UI_2.local_settings import *
except Exception as e:
    print(e)
