# Generated by Django 2.0.1 on 2018-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.AutoField(db_column='AdultId', primary_key=True, serialize=False)),
                ('adult', models.IntegerField(db_column='Adult')),
                ('_active', models.BooleanField(db_column='Active')),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modifieddate', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'Adults',
            },
        ),
        migrations.CreateModel(
            name='AdvanceDay',
            fields=[
                ('id', models.AutoField(db_column='AdvanceDayId', primary_key=True, serialize=False)),
                ('advanceday', models.IntegerField(db_column='AdvanceDay')),
                ('advancedaytext', models.CharField(db_column='AdvanceDayText', max_length=50)),
                ('specifictype', models.IntegerField(db_column='SpecificType')),
                ('_active', models.BooleanField(db_column='Active')),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modifieddate', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'AdvanceDays',
            },
        ),
        migrations.CreateModel(
            name='AirportCodeMaster',
            fields=[
                ('id', models.AutoField(db_column='AirportCodeId', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='AirportCode', max_length=10)),
                ('name', models.CharField(db_column='AirportName', max_length=100)),
                ('_active', models.PositiveSmallIntegerField(db_column='Active', default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'AirportCodes',
            },
        ),
        migrations.CreateModel(
            name='BoardTypeMaster',
            fields=[
                ('id', models.AutoField(db_column='BoardTypeId', primary_key=True, serialize=False)),
                ('boardtypecode', models.CharField(db_column='BoardTypeCode', max_length=50)),
                ('boardtypedescription', models.CharField(db_column='BoardTypeDescription', max_length=50)),
                ('_active', models.BooleanField(db_column='Active')),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modifieddate', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'BoardTypes',
            },
        ),
        migrations.CreateModel(
            name='BookingPeriodMaster',
            fields=[
                ('id', models.AutoField(db_column='BookingPeriodID', primary_key=True, serialize=False)),
                ('bookingperiod', models.CharField(db_column='BookingPeriod', max_length=256)),
                ('_active', models.BooleanField(db_column='Active')),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modifieddate', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'BookingPeriod',
            },
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(db_column='ChildID', primary_key=True, serialize=False)),
                ('child', models.CharField(db_column='Child', max_length=100)),
                ('_active', models.BooleanField(db_column='Active')),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modifieddate', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'Children',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(db_column='CityId', primary_key=True, serialize=False)),
                ('citycode', models.CharField(db_column='CityCode', max_length=10)),
                ('cityname', models.CharField(db_column='CityName', max_length=100)),
                ('active', models.BooleanField(db_column='Active')),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modifieddate', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('id', models.AutoField(db_column='CityId', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CityCode', max_length=10)),
                ('name', models.CharField(db_column='CityName', max_length=100)),
                ('_active', models.PositiveSmallIntegerField(db_column='Active', default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(db_column='CompetitorId', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='CompetitorName', max_length=256)),
                ('active', models.BooleanField(db_column='Active', default=True)),
                ('createdDate', models.DateTimeField(auto_now=True, db_column='CreatedDate')),
                ('updatedDate', models.DateTimeField(auto_now_add=True, db_column='ModifiedDate')),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_CompetitorMaster',
            },
        ),
        migrations.CreateModel(
            name='CompetitorMaster',
            fields=[
                ('id', models.AutoField(db_column='CompetitorId', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='CompetitorName', max_length=256)),
                ('_active', models.BooleanField(db_column='Active', default=True)),
                ('createdDate', models.DateTimeField(auto_now=True, db_column='CreatedDate')),
                ('updatedDate', models.DateTimeField(auto_now_add=True, db_column='ModifiedDate')),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_CompetitorMaster',
            },
        ),
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.AutoField(db_column='CountryID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='CountryName', max_length=30)),
                ('_active', models.PositiveSmallIntegerField(db_column='Active')),
                ('code', models.CharField(db_column='CountryCode', max_length=100)),
                ('timezone', models.CharField(db_column='TimeZone', max_length=35)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_CountryMaster',
            },
        ),
        migrations.CreateModel(
            name='DomainMaster',
            fields=[
                ('id', models.IntegerField(db_column='DomainId', primary_key=True, serialize=False)),
                ('domainname', models.CharField(db_column='DomainName', max_length=50)),
                ('active', models.BooleanField(db_column='Active')),
                ('competitorid', models.PositiveIntegerField(null=True)),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'tbl_DomainMaster',
            },
        ),
        migrations.CreateModel(
            name='FieldGroupMaster',
            fields=[
                ('id', models.AutoField(db_column='GroupID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='GroupName', max_length=50)),
                ('description', models.CharField(db_column='GroupDesc', max_length=50)),
                ('active', models.BooleanField(db_column='Active')),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'tbl_Field_Group_Master',
            },
        ),
        migrations.CreateModel(
            name='FlightSearchType',
            fields=[
                ('id', models.AutoField(db_column='FlightSearchTypeID', primary_key=True, serialize=False)),
                ('flightsearchTypeID', models.CharField(db_column='FlightSearchType', max_length=100)),
                ('_active', models.SmallIntegerField(db_column='Active', default=1)),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modifieddatetime', models.DateTimeField(db_column='ModifiedDatetime', default=None)),
            ],
            options={
                'managed': False,
                'db_table': 'FlightSearchType',
            },
        ),
        migrations.CreateModel(
            name='HotelFlightRequestInputDetail',
            fields=[
                ('id', models.AutoField(db_column='hotelflightrequestinputdetailsId', primary_key=True, serialize=False)),
                ('requesturl', models.CharField(blank=True, db_column='RequestURL', max_length=500, null=True)),
                ('requesttypeid', models.IntegerField(blank=True, db_column='RequestTypeId', null=True)),
                ('createddatetime', models.DateTimeField(auto_now_add=True, db_column='CreatedDatetime')),
                ('updatedatetime', models.DateTimeField(db_column='UpdatedDatetime', default=None)),
                ('fromdate', models.DateTimeField(db_column='FromDate')),
                ('todate', models.DateTimeField(db_column='ToDate')),
                ('DaysOfWeek', models.CharField(db_column='DaysOfWeek', max_length=100)),
                ('rentallength', models.CharField(db_column='RentalLength', max_length=1000)),
                ('advancedates', models.CharField(db_column='AdvanceDates', max_length=1000)),
                ('adults', models.IntegerField(db_column='AdultId')),
                ('children', models.IntegerField(db_column='ChildID')),
                ('crawlmode', models.IntegerField(db_column='CrawlMode')),
                ('StarRating', models.CharField(db_column='StarRating', max_length=500)),
                ('boardtype', models.CharField(db_column='BoardType', max_length=512)),
                ('roomtype', models.CharField(db_column='RoomType', max_length=512)),
                ('suppliers', models.CharField(db_column='CompetitorIds', max_length=512)),
                ('reporttype', models.CharField(db_column='ReportType', max_length=45)),
                ('email', models.CharField(db_column='Email', max_length=1000)),
                ('email_cc', models.CharField(db_column='EmailCC', max_length=1000)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_hotelflightrequestinputdetails',
            },
        ),
        migrations.CreateModel(
            name='HotelFlightRequestsDateDetail',
            fields=[
                ('id', models.AutoField(db_column='hotelflightRequestsDateDetailId', primary_key=True, serialize=False)),
                ('checkindate', models.DateField(db_column='CheckInDate')),
                ('checkoutdate', models.DateField(db_column='CheckOutDate')),
                ('createddatetime', models.DateTimeField(auto_now_add=True, db_column='CreatedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_hotelflightRequestsDateDetail',
            },
        ),
        migrations.CreateModel(
            name='HotelGroup',
            fields=[
                ('id', models.AutoField(db_column='HotelGroupId', primary_key=True, serialize=False)),
                ('hotelgroup', models.CharField(db_column='HotelGroup', max_length=200)),
                ('_active', models.BooleanField(db_column='Active')),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modifieddate', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'HotelGroups',
            },
        ),
        migrations.CreateModel(
            name='HotelGroupDetail',
            fields=[
                ('id', models.AutoField(db_column='hotelgroupdetailsid', primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'HotelGroupDetails',
            },
        ),
        migrations.CreateModel(
            name='HotelGroupMaster',
            fields=[
                ('id', models.AutoField(db_column='HotelGroupId', primary_key=True, serialize=False)),
                ('group', models.CharField(db_column='HotelGroup', max_length=200)),
                ('_active', models.PositiveSmallIntegerField(db_column='Active', default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'HotelGroups',
            },
        ),
        migrations.CreateModel(
            name='HotelMaster',
            fields=[
                ('id', models.AutoField(db_column='HotelId', primary_key=True, serialize=False)),
                ('website_hotel_id', models.CharField(db_column='WebSiteHotelId', max_length=255)),
                ('name', models.CharField(db_column='HotelName', max_length=512)),
                ('address1', models.CharField(db_column='HotelAddress1', max_length=255)),
                ('address2', models.CharField(db_column='HotelAddress2', max_length=255)),
                ('brand', models.CharField(db_column='HotelBrandName', max_length=50)),
                ('post_code', models.CharField(db_column='HotelPostCode', max_length=255)),
                ('match_status', models.PositiveSmallIntegerField(db_column='HotelMatchStatus')),
                ('description', models.CharField(db_column='HotelDescription', max_length=100)),
                ('is_processed', models.PositiveSmallIntegerField(db_column='isProceesed')),
                ('match_hotel_name', models.CharField(db_column='matchhotelname', max_length=100)),
                ('dipbag_sync_id', models.PositiveIntegerField(db_column='DipBagSyncId')),
                ('is_mailed', models.PositiveSmallIntegerField(db_column='IsMailed')),
                ('is_mailed1', models.PositiveSmallIntegerField(db_column='IsMailed1')),
                ('_active', models.PositiveSmallIntegerField(db_column='Active', default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='HotelNameSpecialChars',
            fields=[
                ('id', models.AutoField(db_column='HotelNameSpecialCharsId', primary_key=True, serialize=False)),
                ('SpecialChars', models.CharField(db_column='SpecialChars', max_length=500)),
                ('ReplaceChars', models.CharField(db_column='ReplaceChars', max_length=500)),
                ('IsActive', models.IntegerField(db_column='IsActive')),
                ('AddedDate', models.DateField(db_column='AddedDate')),
            ],
            options={
                'managed': False,
                'db_table': 'HotelNameSpecialChars',
            },
        ),
        migrations.CreateModel(
            name='HotelPOS',
            fields=[
                ('id', models.AutoField(db_column='PointOfSaleId', primary_key=True, serialize=False)),
                ('posale', models.CharField(db_column='PointOfSale', max_length=100)),
                ('poscode', models.CharField(db_column='PointOfSaleCode', max_length=10)),
                ('_active', models.BooleanField(db_column='Active')),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modifieddate', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'HotelPOS',
            },
        ),
        migrations.CreateModel(
            name='HotelRequestInputDetail',
            fields=[
                ('id', models.AutoField(db_column='HotelReqestInputDetailsId', primary_key=True, serialize=False)),
                ('requesturl', models.CharField(blank=True, db_column='RequestURL', max_length=500, null=True)),
                ('requesttypeid', models.IntegerField(blank=True, db_column='RequestTypeId', null=True)),
                ('fromdate', models.DateTimeField(db_column='FromDate')),
                ('todate', models.DateTimeField(db_column='ToDate')),
                ('DaysOfWeek', models.CharField(db_column='DaysOfWeek', max_length=100)),
                ('rentallength', models.CharField(db_column='RentalLength', max_length=1000)),
                ('advancedates', models.CharField(db_column='AdvanceDates', max_length=1000)),
                ('adults', models.IntegerField(db_column='AdultId')),
                ('children', models.IntegerField(db_column='ChildID')),
                ('crawlmode', models.IntegerField(db_column='CrawlMode')),
                ('starrating', models.CharField(db_column='StarRating', max_length=500)),
                ('boardtype', models.CharField(db_column='BoardType', max_length=512)),
                ('roomtype', models.CharField(db_column='RoomType', max_length=512)),
                ('suppliers', models.CharField(db_column='CompetitorIds', max_length=512)),
                ('createddatetime', models.DateTimeField(auto_now_add=True, db_column='CreatedDatetime')),
                ('reporttype', models.CharField(db_column='ReportType', max_length=45)),
                ('email', models.CharField(db_column='Email', max_length=1000)),
                ('email_cc', models.CharField(db_column='EmailCC', max_length=1000)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_hotelrequestinputdetails',
            },
        ),
        migrations.CreateModel(
            name='HotelRequestsDateDetail',
            fields=[
                ('id', models.AutoField(db_column='HotelRequestsDateDetailId', primary_key=True, serialize=False)),
                ('checkindate', models.DateField(db_column='CheckInDate')),
                ('checkoutdate', models.DateField(db_column='CheckOutDate')),
                ('createddatetime', models.DateTimeField(auto_now_add=True, db_column='CreatedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_HotelRequestsDateDetails',
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(db_column='HotelId', primary_key=True, serialize=False)),
                ('WebSiteHotelId', models.IntegerField(db_column='WebSiteHotelId')),
                ('HotelName', models.CharField(db_column='HotelName', max_length=512)),
                ('HotelAddress1', models.CharField(db_column='HotelAddress1', max_length=255)),
                ('HotelAddress2', models.CharField(db_column='HotelAddress2', max_length=255)),
                ('hotelbrandname', models.CharField(db_column='HotelBrandName', max_length=50)),
                ('hotelpostcode', models.CharField(db_column='HotelPostCode', max_length=255)),
                ('hotelmatchstatus', models.BooleanField(db_column='HotelMatchStatus', default=True)),
                ('hoteldescription', models.CharField(db_column='HotelDescription', max_length=100)),
                ('isproceesed', models.BooleanField(db_column='isProceesed', default=True)),
                ('matchhotelname', models.CharField(db_column='matchhotelname', max_length=100)),
                ('dipbagsyncid', models.IntegerField(db_column='DipBagSyncId')),
                ('ismailed', models.BooleanField(db_column='IsMailed', default=True)),
                ('ismailed1', models.BooleanField(db_column='ismailed1', default=True)),
                ('active', models.BooleanField(db_column='Active')),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modifieddate', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='HotelStandardization',
            fields=[
                ('id', models.AutoField(db_column='HotelStandID', primary_key=True, serialize=False)),
                ('RoomType', models.CharField(db_column='RoomType', max_length=500)),
                ('RoomTypeMatch', models.CharField(db_column='RoomTypeMatch', max_length=50)),
                ('Priority', models.IntegerField(db_column='Priority')),
                ('RuleType', models.CharField(db_column='RuleType', max_length=50)),
                ('Active', models.IntegerField(db_column='Active')),
                ('CreatedDateTime', models.DateField(db_column='CreatedDateTime')),
                ('ModifiedDatetime', models.DateField(db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'HotelStandardization',
            },
        ),
        migrations.CreateModel(
            name='KeywordRule',
            fields=[
                ('id', models.IntegerField(db_column='HotelStandId', primary_key=True, serialize=False)),
                ('roomtype', models.CharField(db_column='RoomType', max_length=500)),
                ('roomtypematch', models.CharField(db_column='RoomTypeMatch', max_length=50)),
                ('priority', models.IntegerField(db_column='Priority', max_length=11)),
                ('ruletype', models.CharField(db_column='RuleType', max_length=50)),
                ('active', models.IntegerField(db_column='Active', max_length=10)),
                ('created_by', models.IntegerField(db_column='CreatedBy')),
                ('created_date', models.DateTimeField(db_column='CreatedDateTime')),
                ('modified_by', models.IntegerField(db_column='ModifiedBy')),
                ('modified_date', models.DateTimeField(db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'HotelStandardization',
            },
        ),
        migrations.CreateModel(
            name='PointOfSaleMaster',
            fields=[
                ('id', models.AutoField(db_column='PointOfSaleId', primary_key=True, serialize=False)),
                ('point_of_sale', models.CharField(db_column='PointOfSale', max_length=100)),
                ('code', models.CharField(db_column='PointOfSaleCode', max_length=10)),
                ('_active', models.PositiveSmallIntegerField(db_column='Active', default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'HotelPOS',
            },
        ),
        migrations.CreateModel(
            name='RequestMaster',
            fields=[
                ('id', models.AutoField(db_column='RequestId', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='RequestName', max_length=50)),
                ('_csv_filenames', models.CharField(db_column='RequestFile', max_length=500)),
                ('description', models.TextField(db_column='RequestDescription')),
                ('BLI_id', models.IntegerField(db_column='FK_BliId')),
                ('scheduled_next', models.DateTimeField(db_column='NextScheduleDateTime')),
                ('status_id', models.IntegerField(db_column='FK_StatusId')),
                ('is_pnf_stopper', models.SmallIntegerField(db_column='IsPNFStopper')),
                ('author', models.IntegerField(db_column='CreatedBy')),
                ('modifedby', models.IntegerField(db_column='UpdatedBy')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedDatetime')),
                ('statustypeid', models.IntegerField(db_column='FK_ScheduleTypeId')),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'tbl_RequestMaster',
            },
        ),
        migrations.CreateModel(
            name='RequestModeMaster',
            fields=[
                ('id', models.AutoField(db_column='RequestModeId', primary_key=True, serialize=False)),
                ('requestmode', models.CharField(db_column='RequestMode', max_length=50)),
                ('active', models.BooleanField(db_column='Active')),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modifieddate', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'RequestMode',
            },
        ),
        migrations.CreateModel(
            name='RoomTypeMaster',
            fields=[
                ('id', models.AutoField(db_column='RoomTypeId', primary_key=True, serialize=False)),
                ('roomtype', models.CharField(db_column='RoomType', max_length=50)),
                ('roomtypecode', models.CharField(db_column='RoomTypeCode', max_length=50)),
                ('_active', models.BooleanField(db_column='Active')),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modifieddate', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'RoomTypes',
            },
        ),
        migrations.CreateModel(
            name='ScheduleDate',
            fields=[
                ('scheduleid', models.IntegerField(db_column='ScheduleDatesId', primary_key=True, serialize=False)),
                ('ScheduleDate', models.DateTimeField(db_column='ScheduleDate')),
                ('ScheduleTime', models.TimeField(db_column='ScheduleTime')),
                ('Status', models.CharField(db_column='Status', max_length=10)),
                ('CreatedDatetime', models.DateTimeField(auto_now_add=True, db_column='CreatedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_ScheduleDate',
            },
        ),
        migrations.CreateModel(
            name='ScheduleMaster',
            fields=[
                ('id', models.IntegerField(db_column='ScheduleMasterId', primary_key=True, serialize=False)),
                ('startDate', models.DateField(db_column='StartDate')),
                ('endDate', models.DateField(db_column='EndDate')),
                ('triggerDay', models.CharField(db_column='TriggerDayDate', max_length=200, null=True)),
                ('time', models.TimeField(db_column='Time')),
                ('active', models.BooleanField(db_column='Active', default=1)),
                ('createDt', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modifiedDt', models.DateTimeField(db_column='ModifiedDate', null=True)),
                ('split', models.IntegerField(db_column='Split', null=True)),
                ('frequency', models.IntegerField(db_column='frequency', null=True)),
                ('schedule_type_id', models.IntegerField(db_column='SM_ScheduleTypeId')),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'tbl_ScheduleMaster',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTypeMaster',
            fields=[
                ('id', models.IntegerField(db_column='ShedulId', primary_key=True, serialize=False)),
                ('schedtype', models.CharField(db_column='ScheduleType', max_length=20)),
                ('active', models.BooleanField(db_column='Active', default=1)),
                ('createdDt', models.DateTimeField(db_column='CreatedDate')),
                ('modifiedDt', models.DateTimeField(db_column='ModifiedDate')),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_ScheduleTypeMaster',
            },
        ),
        migrations.CreateModel(
            name='StarRatingMaster',
            fields=[
                ('id', models.AutoField(db_column='StarRatingId', primary_key=True, serialize=False)),
                ('starrating', models.CharField(db_column='StarRating', max_length=50)),
                ('starratingcode', models.CharField(db_column='StarRatingCode', max_length=50)),
                ('_active', models.BooleanField(db_column='Active')),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modifieddate', models.DateTimeField(auto_now=True, db_column='ModifiedDatetime')),
            ],
            options={
                'managed': False,
                'db_table': 'StarRatings',
            },
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('User_ID', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('FirstName', models.CharField(blank=True, db_column='FirstName', max_length=30, null=True)),
                ('LastName', models.CharField(blank=True, db_column='LastName', max_length=30, null=True)),
                ('UserName', models.CharField(blank=True, db_column='UserName', max_length=30, null=True, unique=True)),
                ('Password', models.CharField(blank=True, db_column='password', max_length=30, null=True)),
                ('EmailID', models.CharField(blank=True, db_column='EmailID', max_length=30, null=True)),
                ('Active', models.BooleanField(db_column='Active')),
                ('CreatedDate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True, db_column='LastLogin')),
            ],
            options={
                'abstract': False,
                'db_table': 'tbl_UserMaster',
            },
        ),
    ]
